
/* ESTRUTURA DE UMA TRIGGER */

/* PRECISA MUDAR O DELIMITADOR (;) POR QUALQUER OUTRO SINAL POIS DENTRO DA TRIGGER, HAVERÁ (;) INDICANDO FINAL DE INSTRUÇÃO DE ALGUM BLOCO */
DELIMITER $

CREATE TRIGGER nome_da_trigger
/* INFORMA SE A TRIGGER IRÁ DISPARAR ANTES OU DEPOIS */
BEFORE or AFTER
/* DE UM DESSES COMANDOS DISPONÍVEIS PARA SEREM UTILIZADOS */
INSERT or UPDATE or DELETE
ON nome_da_tabela
FOR EACH ROW
BEGIN -> INICIO


		/* COMANDOS, INSTRUÇÕES SQL */


END -> FIM

DELIMITER ;
