
/*

========== ORGANIZAR FISICAMENTE E LOGICAMENTE UM BANCO DE DADOS ==========

1 - CRIAR O BANCO DE DADOS COM ARQUIVOS PARA OS SETORES DE:
==> MARKETING e VENDAS

2 - CRIAR UM ARQUIVO GERAL

3 - DEIXAR O MDF APENAS COM O DICIONÁRIO DE DADOS

4 - CRIAR DOIS GRUPOS DE ARQUIVOS (PRIMARY - MDF)

*/

CREATE TABLE TBL_EMPRESA
(
	Id INTEGER,
	Nome VARCHAR(50)
)
GO
