
/* =================== TRIGGERS ==================== */

CREATE TABLE TBL_PRODUTOS
(
	IDPRODUTO INTEGER PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL,
	PRECO DECIMAL(18,2) NOT NULL
);
GO

CREATE TABLE TBL_HISTORICO
(
	IDOPERACAO INTEGER PRIMARY KEY IDENTITY,
	PRODUTO VARCHAR(100) NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL,
	PRECOANTIGO DECIMAL(18,2) NOT NULL,
	PRECONOVO DECIMAL(18,2) NOT NULL,
	DATA  DATETIME,
	USUARIO VARCHAR(50),
	MENSAGEM VARCHAR(100)
);
GO

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('LIVRO SQL SERVER ESSENCIAL', 'LIVROS', 102.98);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('LIVRO ORACLE ESSENCIAL', 'LIVROS', 210.41);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('LIVRO C# DO BASICO AO AVANCADO', 'LIVROS', 153.55);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('NOTEBOOK CORE INTEL I7 13 GERACAO', 'COMPUTADORES', 4877.38);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('NOTEBOOK CORE INTEL I7 14 GERACAO', 'COMPUTADORES', 6111.99);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('PC GAMER CORE I5 RYZEN', 'COMPUTADORES', 3999.99);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('MONITOR GAMER 27', 'COMPUTADORES', 999.88);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('MONITOR OLED 32', 'COMPUTADORES', 4000.00);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('IMPRESSORA JATO DE TINTA MULTIFUNCIONAL', 'IMPRESSORAS', 1021.57);

INSERT INTO TBL_PRODUTOS
(NOME, CATEGORIA, PRECO)
VALUES
('MESA PORTATIL COM GAVETAS', 'MOVEIS', 759.30);
GO

SELECT * FROM TBL_PRODUTOS;
/*
IDPRODUTO  NOME                                                                    CATEGORIA                PREÇO

1	                 LIVRO SQL SERVER ESSENCIAL	                        LIVROS	                      102.98
2	                 LIVRO ORACLE ESSENCIAL	                                LIVROS	                      210.41
3	                 LIVRO C# DO BASICO AO AVANCADO	                LIVROS	                      153.55
4	                 NOTEBOOK CORE INTEL I7 13 GERACAO	            COMPUTADORES     	4877.38
5	                 NOTEBOOK CORE INTEL I7 14 GERACAO	            COMPUTADORES     	6111.99
6	                 PC GAMER CORE I5 RYZEN	                                COMPUTADORES     	3999.99
7	                 MONITOR GAMER 27	                                            COMPUTADORES          999.88
8	                 MONITOR OLED 32	                                                COMPUTADORES     	4000.00
9	                 IMPRESSORA JATO DE TINTA MULTIFUNCIONAL	IMPRESSORAS	        1021.57
10	                 MESA PORTATIL COM GAVETAS                         	MOVEIS	                      759.30
*/
SELECT * FROM TBL_HISTORICO;

/* VERIFICA O USUARIO LOGADO */

SELECT SUSER_NAME();
SQL\Vagner

/* TRIGGER DE DADOS -- DML (Data Manipulation Language) */

CREATE TRIGGER TRG_ATUALIZA_PRECO
ON DBO.TBL_PRODUTOS
FOR UPDATE
AS

	DECLARE @IDPRODUTO INTEGER
	DECLARE @PRODUTO VARCHAR(100)
	DECLARE @CATEGORIA VARCHAR(50)
	DECLARE @PRECO DECIMAL(18,2)
	DECLARE @PRECONOVO DECIMAL(18,2)
	DECLARE @DATA  DATETIME
	DECLARE @USUARIO VARCHAR(50)
	DECLARE @MENSAGEM VARCHAR(100)

	/* INFORMAÇÕES VINDO DE TABELAS */
	SELECT @IDPRODUTO       = IDPRODUTO FROM INSERTED 
	SELECT @PRODUTO          =  NOME FROM INSERTED 
	SELECT @CATEGORIA       =  CATEGORIA FROM INSERTED 
	SELECT @PRECO               =  PRECO FROM DELETED 
	SELECT @PRECONOVO      = PRECO FROM INSERTED 
	/* INFORMAÇÕES VINDO DE FUNÇÕES OU LITERAL */
	SET @DATA                         = GETDATE()
	SET @USUARIO                   = SUSER_NAME() 
	SET @MENSAGEM              = 'VALOR INSERIDO PELA TRIGGER (TBL_ATUALIZA_PRECO)' 

	INSERT INTO TBL_HISTORICO
	(PRODUTO, CATEGORIA, PRECOANTIGO, PRECONOVO, DATA, USUARIO, MENSAGEM)
	VALUES
	(@PRODUTO, @CATEGORIA, @PRECO, @PRECONOVO, @DATA, @USUARIO, @MENSAGEM);

	PRINT 'TRIGGER EXECUTADA COM SUCESSO !'

GO

/* EXECUTA UM UPDATE */

UPDATE 
	TBL_PRODUTOS
SET 
	PRECO = 122.88
WHERE 
	IDPRODUTO = 1;
GO

/* CONFERE AS INFORMAÇÕES NAS TABELAS */

SELECT * FROM TBL_PRODUTOS;
/*
1	LIVRO SQL SERVER ESSENCIAL	                                                     LIVROS	                 122.88
2	LIVRO ORACLE ESSENCIAL                                                             LIVROS	                  210.41
3	LIVRO C# DO BASICO AO AVANCADO	                                             LIVROS	                  153.55
4	NOTEBOOK CORE INTEL I7 13 GERACAO	                                     COMPUTADORES	4877.38
5	NOTEBOOK CORE INTEL I7 14 GERACAO	                                     COMPUTADORES	6111.99
6	PC GAMER CORE I5 RYZEN	                                                         COMPUTADORES	3999.99
7	MONITOR GAMER 27	                                                                     COMPUTADORES	  999.88
8	MONITOR OLED 32	                                                                         COMPUTADORES	4000.00
9	IMPRESSORA JATO DE TINTA MULTIFUNCIONAL	                             IMPRESSORAS	    1021.57
10	MESA PORTATIL COM GAVETAS	                                                     MOVEIS	                  759.30
*/
SELECT * FROM TBL_HISTORICO;
/*
IDPRODUTO = 1	
PRODUTO = LIVRO SQL SERVER ESSENCIAL	LIVROS	
PRECO = 102.98	
PRECONOVO = 122.88	
DATA = 2024-10-26 15:59:24.813
USUARIO = SQL\Vagner	
MENSAGEM = VALOR INSERIDO PELA TRIGGER (TBL_ATUALIZA_PRECO)
*/

UPDATE
	TBL_PRODUTOS
SET
	NOME = 'LIVRO C# PARA INICIANTES'
WHERE 
	IDPRODUTO = 1;
GO

SELECT * FROM TBL_PRODUTOS;

/*
1	LIVRO C# PARA INICIANTES  	                                                        LIVROS	                  122.88
2	LIVRO ORACLE ESSENCIAL                                                             LIVROS	                  210.41
3	LIVRO C# DO BASICO AO AVANCADO	                                             LIVROS	                  153.55
4	NOTEBOOK CORE INTEL I7 13 GERACAO	                                     COMPUTADORES	4877.38
5	NOTEBOOK CORE INTEL I7 14 GERACAO	                                     COMPUTADORES	6111.99
6	PC GAMER CORE I5 RYZEN	                                                         COMPUTADORES	3999.99
7	MONITOR GAMER 27	                                                                     COMPUTADORES	  999.88
8	MONITOR OLED 32	                                                                         COMPUTADORES	4000.00
9	IMPRESSORA JATO DE TINTA MULTIFUNCIONAL	                             IMPRESSORAS	    1021.57
10	MESA PORTATIL COM GAVETAS	                                                     MOVEIS	                  759.30
*/

SELECT * FROM TBL_HISTORICO;
/*
1	LIVRO SQL SERVER ESSENCIAL	LIVROS	102.98	122.88	2024-10-26 15:59:24.813	SQL\Vagner	VALOR INSERIDO PELA TRIGGER (TBL_ATUALIZA_PRECO)
2	LIVRO C# PARA INICIANTES	LIVROS	122.88	122.88	2024-10-26 16:15:40.120	SQL\Vagner	VALOR INSERIDO PELA TRIGGER (TBL_ATUALIZA_PRECO)
*/

/* ARRUMA A TRIGGER EM UMA COLUNA */

DROP TRIGGER TRG_ATUALIZA_PRECO;
GO

CREATE TRIGGER TRG_ATUALIZA_PRECO
ON DBO.TBL_PRODUTOS
FOR UPDATE  AS
IF UPDATE (PRECO)
BEGIN

	DECLARE @IDPRODUTO INTEGER
	DECLARE @PRODUTO VARCHAR(100)
	DECLARE @CATEGORIA VARCHAR(50)
	DECLARE @PRECO DECIMAL(18,2)
	DECLARE @PRECONOVO DECIMAL(18,2)
	DECLARE @DATA  DATETIME
	DECLARE @USUARIO VARCHAR(50)
	DECLARE @MENSAGEM VARCHAR(100)

	/* INFORMAÇÕES VINDO DE TABELAS */
	SELECT @IDPRODUTO       = IDPRODUTO FROM INSERTED 
	SELECT @PRODUTO          =  NOME FROM INSERTED 
	SELECT @CATEGORIA       =  CATEGORIA FROM INSERTED 
	SELECT @PRECO               =  PRECO FROM DELETED 
	SELECT @PRECONOVO      = PRECO FROM INSERTED 
	/* INFORMAÇÕES VINDO DE FUNÇÕES OU LITERAL */
	SET @DATA                         = GETDATE()
	SET @USUARIO                   = SUSER_NAME() 
	SET @MENSAGEM              = 'VALOR INSERIDO PELA TRIGGER (TBL_ATUALIZA_PRECO)' 

	INSERT INTO TBL_HISTORICO
	(PRODUTO, CATEGORIA, PRECOANTIGO, PRECONOVO, DATA, USUARIO, MENSAGEM)
	VALUES
	(@PRODUTO, @CATEGORIA, @PRECO, @PRECONOVO, @DATA, @USUARIO, @MENSAGEM);

	PRINT 'TRIGGER EXECUTADA COM SUCESSO !'

END
GO

UPDATE
	TBL_PRODUTOS
SET
	NOME = 'LIVRO JAVA AVANCADO'
WHERE
	IDPRODUTO = 2;
GO

SELECT * FROM TBL_HISTORICO;
/* O HISTÓRICO NÃO FOI ATUALIZADO PORQUE A ATUALIZAÇÃO FOI NO CAMPO NOME
E A TRIGGER SÓ REGISTRA ATUALIZAÇÃO NO PREÇO.

1	LIVRO SQL SERVER ESSENCIAL	LIVROS	102.98	122.88	2024-10-26 15:59:24.813	SQL\Vagner	VALOR INSERIDO PELA TRIGGER (TBL_ATUALIZA_PRECO)
2	LIVRO C# PARA INICIANTES	LIVROS	122.88	122.88	2024-10-26 16:15:40.120	SQL\Vagner	VALOR INSERIDO PELA TRIGGER (TBL_ATUALIZA_PRECO)
*/

SELECT * FROM TBL_PRODUTOS
/*
1	LIVRO C# PARA INICIANTES  	                                                        LIVROS	                  122.88
2	LIVRO JAVA AVANCADO                                                                   LIVROS	                  210.41
3	LIVRO C# DO BASICO AO AVANCADO	                                             LIVROS	                  153.55
4	NOTEBOOK CORE INTEL I7 13 GERACAO	                                     COMPUTADORES	4877.38
5	NOTEBOOK CORE INTEL I7 14 GERACAO	                                     COMPUTADORES	6111.99
6	PC GAMER CORE I5 RYZEN	                                                         COMPUTADORES	3999.99
7	MONITOR GAMER 27	                                                                     COMPUTADORES	  999.88
8	MONITOR OLED 32	                                                                         COMPUTADORES	4000.00
9	IMPRESSORA JATO DE TINTA MULTIFUNCIONAL	                             IMPRESSORAS	    1021.57
10	MESA PORTATIL COM GAVETAS	                                                     MOVEIS	                  759.30
*/
